# Generated by Django 5.1.3 on 2024-11-16 05:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('suggestion', models.TextField()),
                ('allergy_concern', models.TextField(blank=True, null=True)),
                ('suggestion_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity_in_stock', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('supplier', models.CharField(max_length=200)),
                ('expiry_date', models.DateField()),
                ('ingredient_type', models.CharField(choices=[('dairy', 'Dairy'), ('sugar', 'Sugar'), ('flavoring', 'Flavoring'), ('additive', 'Additive')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('flavor_type', models.CharField(choices=[('chocolate', 'Chocolate'), ('vanilla', 'Vanilla'), ('fruity', 'Fruity'), ('spicy', 'Spicy')], max_length=50)),
                ('availability_start', models.DateField()),
                ('availability_end', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
