# Generated by Django 5.1.3 on 2024-11-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_seasonalflavor_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonalflavor',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
